In [3]:
import torch
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from model.base_model import base_model
from transformers import BertModel, BertConfig,BertTokenizer


In [4]:
encoder = BertModel.from_pretrained('bert-base-uncased')

In [5]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [6]:
input_ids

NameError: name 'input_ids' is not defined

In [ ]:
sentence = ["Hello, my dog is cute", "Hello, my cat is cute", "Hello, my dog is cute", "Hello, my cat is cute"]
a = []
for s in sentence:
    input_ids = tokenizer.encode(s, return_tensors='pt',padding = 'max_length',
                                                  truncation = True,
                                                  max_length = 256)
    a.append(input_ids)
outputs = encoder(torch.strach(a))

NameError: name 'tokenizer' is not defined

In [8]:
tokenizer.encode("what is ", return_tensors='pt',padding = 'max_length',)

tensor([[ 101, 2054, 2003,  102,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,  

In [62]:
torch.cat(a,dim = 0).shape

torch.Size([4, 256])

In [60]:
torch.stack(a).shape

torch.Size([4, 1, 256])

In [53]:
outputs[1].shape

torch.Size([4, 768])

In [44]:
input_1 = tokenizer("Hllo, my dog is cute", return_tensors='pt',padding = 'max_length')

In [43]:
input_1

tensor([[  101,  1044,  7174,  1010,  2026,  3899,  2003, 10140,   102,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,  

In [37]:
tokenizer.decode(input_ids[0])

'[CLS] [UNK] [UNK] [UNK] [UNK] [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PA

In [31]:
input_ids.shape

torch.Size([1, 256])

In [32]:
outputs['pooler_output'].shape

torch.Size([1, 768])

In [33]:
outputs[1].shape

torch.Size([1, 768])

In [18]:
input = tokenizer.encode(sentence, return_tensors='pt')

In [20]:
input.shape

torch.Size([1, 3])

In [75]:
import torch
hidden_size = 768
a = torch.rand(5,hidden_size*2)

In [76]:
a[:,(hidden_size//2) : (hidden_size // 2 * 3)].shape

torch.Size([5, 768])

In [74]:
hidden_size/4

192.0

In [79]:
labels = torch.tensor([1,2,3,4,3,3,2,1])

In [81]:
label_matrix = torch.eq(labels.unsqueeze(1), labels.unsqueeze(0)).float()


In [82]:
label_matrix

tensor([[1., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 1., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 1., 1., 0., 0.],
        [0., 0., 1., 0., 1., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 1.]])

In [2]:
import torch

a = torch.rand(5,768*2)

In [3]:
a[:,:768].shape

torch.Size([5, 768])